### ISSUE TITLE
Port to Firefox too (at best, it works out of the box)

### ISSUE THREAD

**Issue by rugk** [sigrons/mydealz_highlighter#2]
It would be great if you could port your browser extension from Chrome/ium also to other browsers like Firefox, i.e. making it a cross-compatible browser extension (“WebExtension”).

See https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/ for more information on how to do that.

**Comment by baui-dev** [comment]
Add the following lines in the manifest.json at the end (after the content-scripts square brackets but before the closing curly braces seperated by a comma):

      "browser_specific_settings": {
          "gecko": {
          "id": "highliter@mydealz.de"
          }
      },

**Comment by sigrons** [comment]
Was added in newest merge.
